name: Pack pack-solution

on:
  push:
    paths:
      - solutions/BRWISolution/**
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Power Platform CLI
        uses: microsoft/powerplatform-actions/actions-install@v1

      - uses: microsoft/powerplatform-actions/pack-solution@v1.9.1
        with:
          solution-file: out/brwi_solution.zip
          solution-folder: solutions/BRWISolution
          solution-type: Both
      - uses: actions/upload-artifact@v4.6.2
        with:
          name: packed-solution
          path: out/
